### ISSUE TITLE
Possible to port this to Linux-based systems like Ubuntu?

### ISSUE THREAD

**Issue by Cormak** [stsrki/KeepAliveHD#1]
I realize this is probably a lot to ask, but will KeepAliveHD ever be ported to Linux? 

If KeepAliveHD can't be ported to Linux but the author has any Linux experience, may I ask how I would achieve the same functionality of KeepAliveHD on an Ubuntu system, using other software? Any software recommendations or step by step instructions as to how you would get the same functionality on a Linux machine?

Thanks for this little piece of software, by the way. Very useful for keeping USB hard drives from spinning down and possibly dying. And thanks for moving to Github after Codeplex shut down.

**Comment by stsrki** [comment]
I really don't have much experience with the Linux so I cannot give you best answer. Maybe you could try use Wine to run KeepAliveHD as it is. If that fails than the only solution is to create new app for or modify KeepAliveHD but that is a problem because it us using WinForms for the UI.
If you have any programming skills it is not that hard to create this type of app.

**Comment by fportegies** [comment]
In linux just write an empty file with crontab:

crontab -e
Add:
* * * * * touch  /var/media/<yourdisk>/emptyfile > /dev/null

That s all

**Comment by fportegies** [comment]
In linux just create empty file every minute in crontab:
crontab -e

* * * * * touch  /var/media/<yourdisk>/emptyfile > /dev/null
